[book]
authors = ["Jack Darlison"]
language = "en"
multilingual = false
src = "src"
title = "The Little Book of Computational Biology"

[build]
build-dir = "docs"
create-missing = true

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/jackdarlison/the-little-book-of-computational-biology"
